### PR TITLE
Fall2020 App update

### LINKED ISSUE #4: Missing infor
On the left-hand side, the "Prerequisites" section is missing.

### LINKED ISSUE #5: Missing infor
On the Overview page, the "Cite this app as:" is missing.

### PR DESCRIPTION
**Pull request by Daehoon7992**
1. Updated id = "tabs"  to id = "pages" .

### CODE REVIEW

**Review by sv101 — APPROVED** [review]
The update focuses on changing the id name for sidebarMenu. The update caused no problems during execution, and all the places that used the old id name have been updated.

**Comment by neilhatfield** [comment]
@sv101 Is this version of the app ready to go? That is,

1. runs without any errors, warnings, or other problems, AND 
2. there are no current GitHub Issues left unaddressed, AND
3. the app meets all aspects of the current Style Guide (including README and DESCRIPTION)?

If so, then add me to the Assignees list for the Pull Request. If not, then you need to change your review to Request Changes, list out what needs to be addressed, and make a recommendation to the priority level (see the guide in Teams).

**Review by sv101 — CHANGES_REQUESTED** [review]
1. The overview page could use more information/instructions about the app. 
2. The files are not organized properly and are missing a docs folder in both branches.
3. The README.md file is incomplete

Recommended priority: High

**Review by tarynmch — CHANGES_REQUESTED** [review]
This app is missing a few crucial features. On the overview page there is no "cite this app as" portion at the bottom. There is no prerequisites page, since this app is to help learn about how outliers and other values impact outputs then there should be a page that describes those impacts in general. On our side of things, alot of the other files should be updated as well, including the Description (Authors & Learning Objectives), README (cover.png is not found), and some now standard things are not there (docs, .lintr, todo). Also, while the instructions are on the overview page, I think it would be beneficial to add some sort of text description to the explore page because there are a lot of visuals and things to adjust (potentially a wellPanel to the sliders to help visually). I also did not notice alt on the plots. While the app itself appears to work fine, I strongly believe a prereq/cite as needs to be added and the files should be updated.

**Review by robchapp — CHANGES_REQUESTED** [review]
This app is not up to the current style guide, it is missing a bunch of files such as the description file, codeowners, and others. There is no prerequisites page, which I think would be helpful in explaining how to move the sliders in ways to better show the effects. Along with not have a cite as on the overview page. On the explore page a problem I found was when you hit the play button to move the outlier, it moves too fast to show any changes, it needs more delay so the summary statistics and graphs can update and show the user the changes. Other than these issues stated.

**Review by robchapp — CHANGES_REQUESTED** [review]
Overall the app works well functionally, however some minor issues, the outline in the app is not made well, and there are no headings for the outline in the server side in the code. Adding that would make it much more readable, and easier to find sections. Also I think the alt text for the graphs could be improved, by describing the skewness, and other information. Last maybe a possibility to add questions to ponder in the explore tab, but not too necessary. Great job overall!

**Review by tarynmch — CHANGES_REQUESTED** [review]
App looks good and runs well. The only thing I noticed to be fixed is the alt text for the images on your prereq page. Right now it says, "fill in." Then I just have two suggestions, on the prerequisites page I would suggest putting the "Summary Statistics for a Sample" section first then the "Plots." I think it makes more sense to put the definitions first then the visuals. I also agree with Rob, adding some application questions would be beneficial.

**Comment by Sburke26** [comment]
Thank you for the reviews.
I made adjustments on the alt texts and prereqs page based on the suggestions. 
Please let me know if there is anything else you notice.

**Review by robchapp — DISMISSED** [review]
Very good job!

**Pull request merged**
